import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:intl/intl.dart';
import 'package:uuid/uuid.dart';
import '../../models/reminder.dart';
import '../../providers/providers.dart';

/// A GenUI component for creating reminders via the AI assistant
class GenUiReminderForm extends ConsumerStatefulWidget {
  final Map<String, dynamic> initialData;

  const GenUiReminderForm({super.key, required this.initialData});

  @override
  ConsumerState<GenUiReminderForm> createState() => _GenUiReminderFormState();
}

class _GenUiReminderFormState extends ConsumerState<GenUiReminderForm> {
  final _formKey = GlobalKey<FormState>();
  late TextEditingController _titleController;
  late TextEditingController _descriptionController;
  late DateTime _selectedDate;
  late ReminderType _selectedType;
  late ReminderPriority _selectedPriority;
  String? _animalTagId;
  bool _isCreating = false;
  bool _isCreated = false;
  String? _errorText;

  @override
  void initState() {
    super.initState();
    _titleController = TextEditingController(
      text: widget.initialData['title'] as String? ?? '',
    );
    _descriptionController = TextEditingController(
      text: widget.initialData['description'] as String? ?? '',
    );
    _animalTagId = widget.initialData['animalTagId'] as String?;

    // Parse due date
    final dueDateStr = widget.initialData['dueDate'] as String?;
    if (dueDateStr != null) {
      _selectedDate =
          DateTime.tryParse(dueDateStr) ??
          DateTime.now().add(const Duration(days: 1));
    } else {
      // Check for relative dates like "tomorrow", "in 3 days"
      final relativeDays = widget.initialData['daysFromNow'] as int?;
      if (relativeDays != null) {
        _selectedDate = DateTime.now().add(Duration(days: relativeDays));
      } else {
        _selectedDate = DateTime.now().add(const Duration(days: 1));
      }
    }

    // Parse type
    final typeStr = widget.initialData['type'] as String?;
    _selectedType = _parseReminderType(typeStr);

    // Parse priority
    final priorityStr = widget.initialData['priority'] as String?;
    _selectedPriority = _parsePriority(priorityStr);
  }

  ReminderType _parseReminderType(String? typeStr) {
    if (typeStr == null) return ReminderType.custom;
    switch (typeStr.toLowerCase()) {
      case 'breeding':
        return ReminderType.breeding;
      case 'health':
        return ReminderType.health;
      case 'weightcheck':
      case 'weight_check':
      case 'weight':
        return ReminderType.weightCheck;
      default:
        return ReminderType.custom;
    }
  }

  ReminderPriority _parsePriority(String? priorityStr) {
    if (priorityStr == null) return ReminderPriority.medium;
    switch (priorityStr.toLowerCase()) {
      case 'low':
        return ReminderPriority.low;
      case 'high':
        return ReminderPriority.high;
      case 'urgent':
        return ReminderPriority.urgent;
      default:
        return ReminderPriority.medium;
    }
  }

  @override
  void dispose() {
    _titleController.dispose();
    _descriptionController.dispose();
    super.dispose();
  }

  Future<void> _createReminder() async {
    if (!_formKey.currentState!.validate()) return;

    final farmId = ref.read(activeFarmIdProvider);
    if (farmId == null) {
      setState(() {
        _errorText = 'No farm selected';
      });
      return;
    }

    setState(() {
      _isCreating = true;
      _errorText = null;
    });

    try {
      final repository = ref.read(reminderRepositoryProvider);

      // Try to find animal by tag ID if provided
      String? animalId;
      if (_animalTagId != null && _animalTagId!.isNotEmpty) {
        final animalRepo = ref.read(animalRepositoryProvider);
        final animal = await animalRepo.getAnimalByTagId(farmId, _animalTagId!);
        animalId = animal?.id;
      }

      final reminder = Reminder(
        id: const Uuid().v4(),
        farmId: farmId,
        animalId: animalId,
        animalTagId: _animalTagId,
        type: _selectedType,
        title: _titleController.text.trim(),
        description: _descriptionController.text.trim().isEmpty
            ? null
            : _descriptionController.text.trim(),
        dueDate: _selectedDate,
        priority: _selectedPriority,
        status: ReminderStatus.pending,
        advanceNoticeDays: 1,
        isAutoGenerated: false,
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
      );

      await repository.createReminder(reminder);

      if (mounted) {
        setState(() {
          _isCreated = true;
          _isCreating = false;
        });
      }
    } catch (e) {
      if (mounted) {
        setState(() {
          _errorText = 'Failed to create reminder: $e';
          _isCreating = false;
        });
      }
    }
  }

  Future<void> _selectDate() async {
    final picked = await showDatePicker(
      context: context,
      initialDate: _selectedDate,
      firstDate: DateTime.now(),
      lastDate: DateTime.now().add(const Duration(days: 365 * 2)),
    );
    if (picked != null && mounted) {
      setState(() {
        _selectedDate = picked;
      });
    }
  }

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);

    if (_isCreated) {
      return Card(
        elevation: 4,
        margin: const EdgeInsets.symmetric(vertical: 8),
        shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
        child: Padding(
          padding: const EdgeInsets.all(16.0),
          child: Column(
            mainAxisSize: MainAxisSize.min,
            children: [
              Icon(Icons.check_circle, color: Colors.green, size: 48),
              const SizedBox(height: 12),
              Text(
                'Reminder Created!',
                style: theme.textTheme.titleMedium?.copyWith(
                  fontWeight: FontWeight.bold,
                ),
              ),
              const SizedBox(height: 8),
              Text(_titleController.text, style: theme.textTheme.bodyMedium),
              const SizedBox(height: 4),
              Text(
                'Due: ${DateFormat('MMM d, yyyy').format(_selectedDate)}',
                style: theme.textTheme.bodySmall?.copyWith(
                  color: theme.colorScheme.onSurfaceVariant,
                ),
              ),
            ],
          ),
        ),
      );
    }

    return Card(
      elevation: 4,
      margin: const EdgeInsets.symmetric(vertical: 8),
      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
      child: ConstrainedBox(
        constraints: const BoxConstraints(maxHeight: 400),
        child: Padding(
          padding: const EdgeInsets.all(16.0),
          child: Form(
            key: _formKey,
            child: SingleChildScrollView(
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.stretch,
                mainAxisSize: MainAxisSize.min,
                children: [
                  Row(
                    children: [
                      Icon(
                        Icons.notification_add,
                        color: theme.colorScheme.primary,
                        size: 20,
                      ),
                      const SizedBox(width: 8),
                      Text(
                        'Create Reminder',
                        style: theme.textTheme.titleMedium,
                      ),
                    ],
                  ),
                  const SizedBox(height: 12),

                  // Title
                  TextFormField(
                    controller: _titleController,
                    decoration: const InputDecoration(
                      labelText: 'Title',
                      border: OutlineInputBorder(),
                      prefixIcon: Icon(Icons.title),
                      isDense: true,
                    ),
                    validator: (value) => value == null || value.trim().isEmpty
                        ? 'Please enter a title'
                        : null,
                  ),
                  const SizedBox(height: 10),

                  // Description - make it single line to save space
                  TextFormField(
                    controller: _descriptionController,
                    decoration: const InputDecoration(
                      labelText: 'Description (optional)',
                      border: OutlineInputBorder(),
                      prefixIcon: Icon(Icons.description),
                      isDense: true,
                    ),
                    maxLines: 1,
                  ),
                  const SizedBox(height: 10),

                  // Date picker
                  InkWell(
                    onTap: _selectDate,
                    child: InputDecorator(
                      decoration: const InputDecoration(
                        labelText: 'Due Date',
                        border: OutlineInputBorder(),
                        prefixIcon: Icon(Icons.calendar_today),
                        isDense: true,
                      ),
                      child: Row(
                        mainAxisAlignment: MainAxisAlignment.spaceBetween,
                        children: [
                          Text(DateFormat('MMM d, yyyy').format(_selectedDate)),
                          const Icon(Icons.arrow_drop_down, size: 20),
                        ],
                      ),
                    ),
                  ),
                  const SizedBox(height: 10),

                  // Type and Priority row
                  Row(
                    children: [
                      Expanded(
                        child: DropdownButtonFormField<ReminderType>(
                          initialValue: _selectedType,
                          decoration: const InputDecoration(
                            labelText: 'Type',
                            border: OutlineInputBorder(),
                            isDense: true,
                            contentPadding: EdgeInsets.symmetric(
                              horizontal: 10,
                              vertical: 12,
                            ),
                          ),
                          items: ReminderType.values.map((type) {
                            return DropdownMenuItem(
                              value: type,
                              child: Row(
                                mainAxisSize: MainAxisSize.min,
                                children: [
                                  Icon(_getTypeIcon(type), size: 16),
                                  const SizedBox(width: 4),
                                  Text(
                                    type.displayName,
                                    style: const TextStyle(fontSize: 13),
                                  ),
                                ],
                              ),
                            );
                          }).toList(),
                          onChanged: (value) {
                            if (value != null) {
                              setState(() {
                                _selectedType = value;
                              });
                            }
                          },
                        ),
                      ),
                      const SizedBox(width: 8),
                      Expanded(
                        child: DropdownButtonFormField<ReminderPriority>(
                          initialValue: _selectedPriority,
                          decoration: const InputDecoration(
                            labelText: 'Priority',
                            border: OutlineInputBorder(),
                            isDense: true,
                            contentPadding: EdgeInsets.symmetric(
                              horizontal: 10,
                              vertical: 12,
                            ),
                          ),
                          items: ReminderPriority.values.map((priority) {
                            return DropdownMenuItem(
                              value: priority,
                              child: Row(
                                mainAxisSize: MainAxisSize.min,
                                children: [
                                  Container(
                                    width: 10,
                                    height: 10,
                                    decoration: BoxDecoration(
                                      color: _getPriorityColor(priority),
                                      shape: BoxShape.circle,
                                    ),
                                  ),
                                  const SizedBox(width: 4),
                                  Text(
                                    priority.displayName,
                                    style: const TextStyle(fontSize: 13),
                                  ),
                                ],
                              ),
                            );
                          }).toList(),
                          onChanged: (value) {
                            if (value != null) {
                              setState(() {
                                _selectedPriority = value;
                              });
                            }
                          },
                        ),
                      ),
                    ],
                  ),
                  const SizedBox(height: 10),

                  // Animal tag (optional)
                  TextFormField(
                    initialValue: _animalTagId,
                    decoration: const InputDecoration(
                      labelText: 'Animal Tag (optional)',
                      border: OutlineInputBorder(),
                      prefixIcon: Icon(Icons.pets),
                      isDense: true,
                    ),
                    onChanged: (value) {
                      _animalTagId = value.isEmpty ? null : value;
                    },
                  ),

                  if (_errorText != null) ...[
                    const SizedBox(height: 8),
                    Text(
                      _errorText!,
                      style: TextStyle(
                        color: theme.colorScheme.error,
                        fontSize: 12,
                      ),
                    ),
                  ],

                  const SizedBox(height: 12),

                  // Create button
                  ElevatedButton.icon(
                    onPressed: _isCreating ? null : _createReminder,
                    icon: _isCreating
                        ? const SizedBox(
                            width: 16,
                            height: 16,
                            child: CircularProgressIndicator(strokeWidth: 2),
                          )
                        : const Icon(Icons.add_alert, size: 18),
                    label: Text(
                      _isCreating ? 'Creating...' : 'Create Reminder',
                    ),
                    style: ElevatedButton.styleFrom(
                      padding: const EdgeInsets.symmetric(vertical: 10),
                    ),
                  ),
                ],
              ),
            ),
          ),
        ),
      ),
    );
  }

  IconData _getTypeIcon(ReminderType type) {
    switch (type) {
      case ReminderType.breeding:
        return Icons.favorite;
      case ReminderType.health:
        return Icons.medical_services;
      case ReminderType.weightCheck:
        return Icons.scale;
      case ReminderType.custom:
        return Icons.notifications;
    }
  }

  Color _getPriorityColor(ReminderPriority priority) {
    switch (priority) {
      case ReminderPriority.low:
        return Colors.green;
      case ReminderPriority.medium:
        return Colors.orange;
      case ReminderPriority.high:
        return Colors.deepOrange;
      case ReminderPriority.urgent:
        return Colors.red;
    }
  }
}
