import 'package:flutter_test/flutter_test.dart';
import 'package:manage/models/reminder.dart';

void main() {
  group('ReminderType', () {
    test('all types are defined', () {
      expect(ReminderType.values.length, 4);
      expect(ReminderType.values, contains(ReminderType.breeding));
      expect(ReminderType.values, contains(ReminderType.health));
      expect(ReminderType.values, contains(ReminderType.weightCheck));
      expect(ReminderType.values, contains(ReminderType.custom));
    });

    test('displayName returns correct values', () {
      expect(ReminderType.breeding.displayName, 'Breeding');
      expect(ReminderType.health.displayName, 'Health');
      expect(ReminderType.weightCheck.displayName, 'Weight Check');
      expect(ReminderType.custom.displayName, 'Custom');
    });

    test('iconName returns correct values', () {
      expect(ReminderType.breeding.iconName, 'favorite');
      expect(ReminderType.health.iconName, 'medical_services');
      expect(ReminderType.weightCheck.iconName, 'scale');
      expect(ReminderType.custom.iconName, 'notifications');
    });
  });

  group('ReminderPriority', () {
    test('all priorities are defined', () {
      expect(ReminderPriority.values.length, 4);
      expect(ReminderPriority.values, contains(ReminderPriority.low));
      expect(ReminderPriority.values, contains(ReminderPriority.medium));
      expect(ReminderPriority.values, contains(ReminderPriority.high));
      expect(ReminderPriority.values, contains(ReminderPriority.urgent));
    });

    test('displayName returns correct values', () {
      expect(ReminderPriority.low.displayName, 'Low');
      expect(ReminderPriority.medium.displayName, 'Medium');
      expect(ReminderPriority.high.displayName, 'High');
      expect(ReminderPriority.urgent.displayName, 'Urgent');
    });

    test('sortOrder returns correct order', () {
      expect(ReminderPriority.urgent.sortOrder, 0);
      expect(ReminderPriority.high.sortOrder, 1);
      expect(ReminderPriority.medium.sortOrder, 2);
      expect(ReminderPriority.low.sortOrder, 3);
    });

    test('priorities sort correctly by sortOrder', () {
      final priorities = [
        ReminderPriority.low,
        ReminderPriority.urgent,
        ReminderPriority.medium,
        ReminderPriority.high,
      ];

      priorities.sort((a, b) => a.sortOrder.compareTo(b.sortOrder));

      expect(priorities[0], ReminderPriority.urgent);
      expect(priorities[1], ReminderPriority.high);
      expect(priorities[2], ReminderPriority.medium);
      expect(priorities[3], ReminderPriority.low);
    });
  });

  group('ReminderStatus', () {
    test('all statuses are defined', () {
      expect(ReminderStatus.values.length, 4);
      expect(ReminderStatus.values, contains(ReminderStatus.pending));
      expect(ReminderStatus.values, contains(ReminderStatus.completed));
      expect(ReminderStatus.values, contains(ReminderStatus.dismissed));
      expect(ReminderStatus.values, contains(ReminderStatus.snoozed));
    });
  });

  group('Reminder Model', () {
    late DateTime now;
    late Reminder reminder;

    setUp(() {
      now = DateTime(2026, 1, 10, 10, 0);
      reminder = Reminder(
        id: 'reminder-001',
        farmId: 'farm-001',
        animalId: 'animal-001',
        animalTagId: 'PIG-001',
        type: ReminderType.health,
        title: 'Vaccination Due',
        description: 'Annual PRRS vaccination is due',
        dueDate: now,
        priority: ReminderPriority.high,
        status: ReminderStatus.pending,
        sourceRecordId: 'health-001',
        sourceType: 'health',
        advanceNoticeDays: 3,
        isAutoGenerated: true,
        createdAt: now.subtract(const Duration(days: 3)),
        updatedAt: now.subtract(const Duration(days: 3)),
      );
    });

    test('should create a Reminder instance with all properties', () {
      expect(reminder.id, 'reminder-001');
      expect(reminder.farmId, 'farm-001');
      expect(reminder.animalId, 'animal-001');
      expect(reminder.animalTagId, 'PIG-001');
      expect(reminder.type, ReminderType.health);
      expect(reminder.title, 'Vaccination Due');
      expect(reminder.priority, ReminderPriority.high);
      expect(reminder.status, ReminderStatus.pending);
      expect(reminder.isAutoGenerated, true);
    });

    test('isDueToday returns true when due date is today', () {
      final todayReminder = Reminder(
        id: 'reminder-today',
        farmId: 'farm-001',
        type: ReminderType.custom,
        title: 'Today Reminder',
        dueDate: DateTime.now(),
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
      );

      expect(todayReminder.isDueToday, true);
    });

    test('isDueToday returns false when due date is not today', () {
      final tomorrowReminder = Reminder(
        id: 'reminder-tomorrow',
        farmId: 'farm-001',
        type: ReminderType.custom,
        title: 'Tomorrow Reminder',
        dueDate: DateTime.now().add(const Duration(days: 1)),
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
      );

      expect(tomorrowReminder.isDueToday, false);
    });

    test('isOverdue returns true for past due pending reminder', () {
      final overdueReminder = Reminder(
        id: 'reminder-overdue',
        farmId: 'farm-001',
        type: ReminderType.health,
        title: 'Overdue Reminder',
        dueDate: DateTime.now().subtract(const Duration(days: 2)),
        status: ReminderStatus.pending,
        createdAt: DateTime.now().subtract(const Duration(days: 5)),
        updatedAt: DateTime.now().subtract(const Duration(days: 5)),
      );

      expect(overdueReminder.isOverdue, true);
    });

    test('isOverdue returns false for completed reminder', () {
      final completedReminder = Reminder(
        id: 'reminder-completed',
        farmId: 'farm-001',
        type: ReminderType.health,
        title: 'Completed Reminder',
        dueDate: DateTime.now().subtract(const Duration(days: 2)),
        status: ReminderStatus.completed,
        createdAt: DateTime.now().subtract(const Duration(days: 5)),
        updatedAt: DateTime.now(),
      );

      expect(completedReminder.isOverdue, false);
    });

    test('isOverdue returns false for future reminder', () {
      final futureReminder = Reminder(
        id: 'reminder-future',
        farmId: 'farm-001',
        type: ReminderType.health,
        title: 'Future Reminder',
        dueDate: DateTime.now().add(const Duration(days: 5)),
        status: ReminderStatus.pending,
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
      );

      expect(futureReminder.isOverdue, false);
    });

    test('shouldShow returns true within advance notice period', () {
      final advanceReminder = Reminder(
        id: 'reminder-advance',
        farmId: 'farm-001',
        type: ReminderType.breeding,
        title: 'Upcoming Farrowing',
        dueDate: DateTime.now().add(const Duration(days: 2)),
        advanceNoticeDays: 3,
        status: ReminderStatus.pending,
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
      );

      expect(advanceReminder.shouldShow, true);
    });

    test('shouldShow returns false if snoozed until future date', () {
      final snoozedReminder = Reminder(
        id: 'reminder-snoozed',
        farmId: 'farm-001',
        type: ReminderType.custom,
        title: 'Snoozed Reminder',
        dueDate: DateTime.now(),
        status: ReminderStatus.snoozed,
        snoozedUntil: DateTime.now().add(const Duration(hours: 2)),
        createdAt: DateTime.now().subtract(const Duration(days: 1)),
        updatedAt: DateTime.now(),
      );

      expect(snoozedReminder.shouldShow, false);
    });

    test('toSupabase should convert to map correctly', () {
      final map = reminder.toSupabase();

      expect(map['farm_id'], 'farm-001');
      expect(map['animal_id'], 'animal-001');
      expect(map['type'], 'health');
      expect(map['title'], 'Vaccination Due');
      expect(map['priority'], 'high');
      expect(map['status'], 'pending');
      expect(map['is_auto_generated'], true);
    });

    test('copyWith should create new instance with updated values', () {
      final updatedReminder = reminder.copyWith(
        status: ReminderStatus.completed,
        priority: ReminderPriority.low,
      );

      expect(updatedReminder.status, ReminderStatus.completed);
      expect(updatedReminder.priority, ReminderPriority.low);
      expect(updatedReminder.id, reminder.id); // Unchanged
      expect(updatedReminder.title, reminder.title); // Unchanged
    });

    test('should handle breeding reminder type', () {
      final breedingReminder = Reminder(
        id: 'reminder-breeding',
        farmId: 'farm-001',
        animalId: 'animal-002',
        animalTagId: 'PIG-002',
        type: ReminderType.breeding,
        title: 'Expected Farrowing',
        description: 'Sow expected to farrow',
        dueDate: DateTime.now().add(const Duration(days: 7)),
        priority: ReminderPriority.urgent,
        sourceRecordId: 'breeding-001',
        sourceType: 'breeding',
        isAutoGenerated: true,
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
      );

      expect(breedingReminder.type, ReminderType.breeding);
      expect(breedingReminder.sourceType, 'breeding');
      expect(breedingReminder.priority, ReminderPriority.urgent);
    });

    test('should handle weight check reminder type', () {
      final weightReminder = Reminder(
        id: 'reminder-weight',
        farmId: 'farm-001',
        animalId: 'animal-003',
        type: ReminderType.weightCheck,
        title: 'Weekly Weight Check',
        dueDate: DateTime.now().add(const Duration(days: 1)),
        priority: ReminderPriority.medium,
        advanceNoticeDays: 1,
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
      );

      expect(weightReminder.type, ReminderType.weightCheck);
      expect(weightReminder.advanceNoticeDays, 1);
    });

    test('should handle custom user-created reminder', () {
      final customReminder = Reminder(
        id: 'reminder-custom',
        farmId: 'farm-001',
        type: ReminderType.custom,
        title: 'Order more feed',
        description: 'Running low on pig feed, need to order more',
        dueDate: DateTime.now().add(const Duration(days: 3)),
        priority: ReminderPriority.high,
        createdBy: 'user-001',
        isAutoGenerated: false,
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
      );

      expect(customReminder.type, ReminderType.custom);
      expect(customReminder.createdBy, 'user-001');
      expect(customReminder.isAutoGenerated, false);
      expect(customReminder.animalId, isNull);
    });
  });
}
