/// Types of reminders
enum ReminderType {
  /// Breeding related - heat cycle, expected farrowing
  breeding,

  /// Health related - vaccination due, medication schedule, follow-up
  health,

  /// Weight check reminder
  weightCheck,

  /// Custom user-created reminder
  custom,
}

/// Priority levels for reminders
enum ReminderPriority { low, medium, high, urgent }

/// Status of a reminder
enum ReminderStatus { pending, completed, dismissed, snoozed }

/// Extension for ReminderType display
extension ReminderTypeExtension on ReminderType {
  String get displayName {
    switch (this) {
      case ReminderType.breeding:
        return 'Breeding';
      case ReminderType.health:
        return 'Health';
      case ReminderType.weightCheck:
        return 'Weight Check';
      case ReminderType.custom:
        return 'Custom';
    }
  }

  String get iconName {
    switch (this) {
      case ReminderType.breeding:
        return 'favorite';
      case ReminderType.health:
        return 'medical_services';
      case ReminderType.weightCheck:
        return 'scale';
      case ReminderType.custom:
        return 'notifications';
    }
  }
}

/// Extension for ReminderPriority display
extension ReminderPriorityExtension on ReminderPriority {
  String get displayName {
    switch (this) {
      case ReminderPriority.low:
        return 'Low';
      case ReminderPriority.medium:
        return 'Medium';
      case ReminderPriority.high:
        return 'High';
      case ReminderPriority.urgent:
        return 'Urgent';
    }
  }

  int get sortOrder {
    switch (this) {
      case ReminderPriority.urgent:
        return 0;
      case ReminderPriority.high:
        return 1;
      case ReminderPriority.medium:
        return 2;
      case ReminderPriority.low:
        return 3;
    }
  }
}

/// A reminder/notification for farm activities
class Reminder {
  final String id;
  final String farmId;
  final String? animalId;
  final String? animalTagId; // Denormalized for display
  final ReminderType type;
  final String title;
  final String? description;
  final DateTime dueDate;
  final ReminderPriority priority;
  final ReminderStatus status;

  /// Reference to the source record (breeding record ID, health record ID, etc.)
  final String? sourceRecordId;

  /// Type of source record for navigation
  final String? sourceType; // 'breeding', 'health', etc.

  /// When to show reminder before due date (in days)
  final int advanceNoticeDays;

  /// User ID who created the reminder (null for auto-generated)
  final String? createdBy;

  /// Whether this reminder was auto-generated
  final bool isAutoGenerated;

  /// Snooze until this date (if snoozed)
  final DateTime? snoozedUntil;

  final DateTime createdAt;
  final DateTime updatedAt;

  Reminder({
    required this.id,
    required this.farmId,
    this.animalId,
    this.animalTagId,
    required this.type,
    required this.title,
    this.description,
    required this.dueDate,
    this.priority = ReminderPriority.medium,
    this.status = ReminderStatus.pending,
    this.sourceRecordId,
    this.sourceType,
    this.advanceNoticeDays = 1,
    this.createdBy,
    this.isAutoGenerated = false,
    this.snoozedUntil,
    required this.createdAt,
    required this.updatedAt,
  });

  /// Check if reminder is due today
  bool get isDueToday {
    final now = DateTime.now();
    return dueDate.year == now.year &&
        dueDate.month == now.month &&
        dueDate.day == now.day;
  }

  /// Check if reminder is overdue
  bool get isOverdue {
    return dueDate.isBefore(DateTime.now()) && status == ReminderStatus.pending;
  }

  /// Check if reminder should be shown (considering advance notice)
  bool get shouldShow {
    if (status != ReminderStatus.pending) return false;
    if (snoozedUntil != null && DateTime.now().isBefore(snoozedUntil!)) {
      return false;
    }
    final showDate = dueDate.subtract(Duration(days: advanceNoticeDays));
    return DateTime.now().isAfter(showDate) ||
        DateTime.now().isAtSameMomentAs(showDate);
  }

  /// Days until due (negative if overdue)
  int get daysUntilDue {
    final now = DateTime.now();
    final today = DateTime(now.year, now.month, now.day);
    final due = DateTime(dueDate.year, dueDate.month, dueDate.day);
    return due.difference(today).inDays;
  }

  /// Human-readable due date text
  String get dueDateText {
    final days = daysUntilDue;
    if (days < 0) {
      return '${-days} day${days == -1 ? '' : 's'} overdue';
    } else if (days == 0) {
      return 'Due today';
    } else if (days == 1) {
      return 'Due tomorrow';
    } else if (days <= 7) {
      return 'Due in $days days';
    } else {
      return 'Due on ${_formatDate(dueDate)}';
    }
  }

  String _formatDate(DateTime date) {
    return '${date.day}/${date.month}/${date.year}';
  }

  /// Create from Supabase row (snake_case fields)
  factory Reminder.fromSupabase(Map<String, dynamic> data) {
    return Reminder(
      id: data['id'] ?? '',
      farmId: data['farm_id'] ?? '',
      animalId: data['animal_id'],
      animalTagId: data['animal_tag_id'],
      type: ReminderType.values.firstWhere(
        (e) => e.name == data['type'],
        orElse: () => ReminderType.custom,
      ),
      title: data['title'] ?? '',
      description: data['description'],
      dueDate: DateTime.parse(
        data['due_date'] ?? DateTime.now().toIso8601String(),
      ),
      priority: ReminderPriority.values.firstWhere(
        (e) => e.name == data['priority'],
        orElse: () => ReminderPriority.medium,
      ),
      status: ReminderStatus.values.firstWhere(
        (e) => e.name == data['status'],
        orElse: () => ReminderStatus.pending,
      ),
      sourceRecordId: data['source_record_id'],
      sourceType: data['source_type'],
      advanceNoticeDays: data['advance_notice_days'] ?? 1,
      createdBy: data['created_by'],
      isAutoGenerated: data['is_auto_generated'] ?? false,
      snoozedUntil: data['snoozed_until'] != null
          ? DateTime.parse(data['snoozed_until'])
          : null,
      createdAt: DateTime.parse(
        data['created_at'] ?? DateTime.now().toIso8601String(),
      ),
      updatedAt: DateTime.parse(
        data['updated_at'] ?? DateTime.now().toIso8601String(),
      ),
    );
  }

  /// Convert to Supabase row (snake_case fields)
  Map<String, dynamic> toSupabase() {
    return {
      'farm_id': farmId,
      'animal_id': animalId,
      'animal_tag_id': animalTagId,
      'type': type.name,
      'title': title,
      'description': description,
      'due_date': dueDate.toIso8601String(),
      'priority': priority.name,
      'status': status.name,
      'source_record_id': sourceRecordId,
      'source_type': sourceType,
      'advance_notice_days': advanceNoticeDays,
      'is_auto_generated': isAutoGenerated,
      'snoozed_until': snoozedUntil?.toIso8601String(),
      'created_at': createdAt.toIso8601String(),
      'updated_at': updatedAt.toIso8601String(),
    };
  }

  Reminder copyWith({
    String? id,
    String? farmId,
    String? animalId,
    String? animalTagId,
    ReminderType? type,
    String? title,
    String? description,
    DateTime? dueDate,
    ReminderPriority? priority,
    ReminderStatus? status,
    String? sourceRecordId,
    String? sourceType,
    int? advanceNoticeDays,
    String? createdBy,
    bool? isAutoGenerated,
    DateTime? snoozedUntil,
    DateTime? createdAt,
    DateTime? updatedAt,
  }) {
    return Reminder(
      id: id ?? this.id,
      farmId: farmId ?? this.farmId,
      animalId: animalId ?? this.animalId,
      animalTagId: animalTagId ?? this.animalTagId,
      type: type ?? this.type,
      title: title ?? this.title,
      description: description ?? this.description,
      dueDate: dueDate ?? this.dueDate,
      priority: priority ?? this.priority,
      status: status ?? this.status,
      sourceRecordId: sourceRecordId ?? this.sourceRecordId,
      sourceType: sourceType ?? this.sourceType,
      advanceNoticeDays: advanceNoticeDays ?? this.advanceNoticeDays,
      createdBy: createdBy ?? this.createdBy,
      isAutoGenerated: isAutoGenerated ?? this.isAutoGenerated,
      snoozedUntil: snoozedUntil ?? this.snoozedUntil,
      createdAt: createdAt ?? this.createdAt,
      updatedAt: updatedAt ?? this.updatedAt,
    );
  }
}

/// Settings for reminder notifications
class ReminderSettings {
  final String farmId;
  final bool breedingRemindersEnabled;
  final bool healthRemindersEnabled;
  final bool weightCheckRemindersEnabled;
  final int defaultAdvanceNoticeDays;
  final int weightCheckIntervalDays; // How often to remind for weight checks
  final TimeOfDay? quietHoursStart;
  final TimeOfDay? quietHoursEnd;

  ReminderSettings({
    required this.farmId,
    this.breedingRemindersEnabled = true,
    this.healthRemindersEnabled = true,
    this.weightCheckRemindersEnabled = true,
    this.defaultAdvanceNoticeDays = 3,
    this.weightCheckIntervalDays = 7,
    this.quietHoursStart,
    this.quietHoursEnd,
  });

  /// Create from Supabase row (snake_case fields)
  factory ReminderSettings.fromSupabase(Map<String, dynamic> data) {
    return ReminderSettings(
      farmId: data['farm_id'] ?? '',
      breedingRemindersEnabled: data['breeding_reminders_enabled'] ?? true,
      healthRemindersEnabled: data['health_reminders_enabled'] ?? true,
      weightCheckRemindersEnabled:
          data['weight_check_reminders_enabled'] ?? true,
      defaultAdvanceNoticeDays: data['default_advance_notice_days'] ?? 3,
      weightCheckIntervalDays: data['weight_check_interval_days'] ?? 7,
      quietHoursStart: data['quiet_hours_start'] != null
          ? TimeOfDay(
              hour: data['quiet_hours_start']['hour'],
              minute: data['quiet_hours_start']['minute'],
            )
          : null,
      quietHoursEnd: data['quiet_hours_end'] != null
          ? TimeOfDay(
              hour: data['quiet_hours_end']['hour'],
              minute: data['quiet_hours_end']['minute'],
            )
          : null,
    );
  }

  /// Convert to Supabase row (snake_case fields)
  Map<String, dynamic> toSupabase() {
    return {
      'farm_id': farmId,
      'breeding_reminders_enabled': breedingRemindersEnabled,
      'health_reminders_enabled': healthRemindersEnabled,
      'weight_check_reminders_enabled': weightCheckRemindersEnabled,
      'default_advance_notice_days': defaultAdvanceNoticeDays,
      'weight_check_interval_days': weightCheckIntervalDays,
      'quiet_hours_start': quietHoursStart != null
          ? {'hour': quietHoursStart!.hour, 'minute': quietHoursStart!.minute}
          : null,
      'quiet_hours_end': quietHoursEnd != null
          ? {'hour': quietHoursEnd!.hour, 'minute': quietHoursEnd!.minute}
          : null,
    };
  }

  ReminderSettings copyWith({
    String? farmId,
    bool? breedingRemindersEnabled,
    bool? healthRemindersEnabled,
    bool? weightCheckRemindersEnabled,
    int? defaultAdvanceNoticeDays,
    int? weightCheckIntervalDays,
    TimeOfDay? quietHoursStart,
    TimeOfDay? quietHoursEnd,
  }) {
    return ReminderSettings(
      farmId: farmId ?? this.farmId,
      breedingRemindersEnabled:
          breedingRemindersEnabled ?? this.breedingRemindersEnabled,
      healthRemindersEnabled:
          healthRemindersEnabled ?? this.healthRemindersEnabled,
      weightCheckRemindersEnabled:
          weightCheckRemindersEnabled ?? this.weightCheckRemindersEnabled,
      defaultAdvanceNoticeDays:
          defaultAdvanceNoticeDays ?? this.defaultAdvanceNoticeDays,
      weightCheckIntervalDays:
          weightCheckIntervalDays ?? this.weightCheckIntervalDays,
      quietHoursStart: quietHoursStart ?? this.quietHoursStart,
      quietHoursEnd: quietHoursEnd ?? this.quietHoursEnd,
    );
  }
}

/// Helper class for TimeOfDay serialization
class TimeOfDay {
  final int hour;
  final int minute;

  const TimeOfDay({required this.hour, required this.minute});
}
